// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    {
      type: "html",
      value: `<p style="color: var(--ifm-color-secondary-darkest)">DOCUMENTATION</p>`,
      defaultStyle: true,
    },
    {
      type: "doc",
      id: "introduction",
      label: "👋 Welcome to WordLift",
    },
    {
      type: "category",
      label: "🛠️ Core Features",
      items: [
        {
          type: "category",
          label: "🏗️ Knowledge Graph",
          items: [
            {
              type: "category",
              label: "Enterprise Solutions",
              items: [
                {
                  type: "doc",
                  id: "knowledge-graph/botify",
                  label: "Botify Integration"
                },
                {
                  type: "doc",
                  id: "knowledge-graph/sitemap-import",
                  label: "Sitemap Import"
                },
                {
                  type: "doc",
                  id: "knowledge-graph/analytics-api",
                  label: "Analytics Import"
                },
              ]
            },
            {
              type: "doc",
              id: "product-knowledge-graph-builder/introduction",
              label: "Product Knowledge Graph"
            },
            {
              type: "doc",
              id: "cloud/index",
              label: "Install the WordLift Cloud script"
            },
            {
              type: "doc",
              id: "cloud/google-tag-manager",
              label: "WordLift Cloud via GTM"
            },
          ],
        },
        {
          type: "category",
          label: "🤖 Smart Content",
          items: [
            {
              type: "doc",
              id: "agent-wordlift/index",
              label: "Agent WordLift"
            },
            {
              type: "doc",
              id: "content-generation/content-generation",
              label: "Content Generation"
            },
            {
              type: "doc",
              id: "llm-connectors/index",
              label: "AI & LLM Integrations"
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "🔌 Platform Integrations",
      items: [
        {
          type: "category",
          label: "CMS & E-commerce",
          items: [
            {
              type: "doc",
              id: "wordpress-plugin/index",
              label: "WordPress Plugin"
            },
            {
              type: "doc",
              id: "woocommerce/introduction",
              label: "WooCommerce SEO"
            },
          ],
        },
        {
          type: "category",
          label: "Marketing Tools",
          items: [
            {
              type: "doc",
              id: "seo-add-on-google-sheets/introduction",
              label: "Google Sheets Add-on"
            },
            {
              type: "doc",
              id: "looker-studio-connector/introduction",
              label: "Google Looker Studio"
            },
            {
              type: "doc",
              id: "marketing-automation/zapier/introduction",
              label: "Zapier Integration"
            },
            {
              type: "doc",
              id: "marketing-automation/power-automate/introduction",
              label: "Microsoft Power Automate"
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "📚 Developer Resources",
      items: [
        {
          type: "link",
          href: "/category/api",
          label: "API Documentation"
        },
      ],
    },
  ],
  // Keep all existing sidebar configurations unchanged
  "agent-wordlift": [
    {
      type: "autogenerated",
      dirName: "agent-wordlift",
    },
  ],
  "knowledge-graph": [
    {
      type: "autogenerated",
      dirName: "knowledge-graph",
    },
  ],
  "wordpress-plugin": [
    {
      type: "autogenerated",
      dirName: "wordpress-plugin",
    },
  ],
  "product-knowledge-graph-builder": [
    {
      type: "autogenerated",
      dirName: "product-knowledge-graph-builder",
    },
  ],
  "llm-connectors": [
    {
      type: "autogenerated",
      dirName: "llm-connectors",
    },
  ],
  "content-generation": [
    {
      type: "autogenerated",
      dirName: "content-generation",
    },
  ],
  "marketing-automation": [
    {
      type: "autogenerated",
      dirName: "marketing-automation",
    },
  ],
  wordlift: [
    {
      type: "category",
      label: "API",
      link: {
        type: "generated-index",
        slug: "/category/api",
      },
      items: [
        {
          type: "category",
          label: "Agent WordLift",
          items: require("./docs/api/agent/sidebar.ts").default,
        },
        {
          type: "category",
          label: "Audit",
          items: require("./docs/api/audit/sidebar.ts").default,
        },
        {
          type: "category",
          label: "Analysis",
          items: require("./docs/api/analysis/sidebar.ts").default,
        },
        {
          type: "category",
          label: "Classification",
          items: require("./docs/api/classification/sidebar.ts").default,
        },
        {
          type: "category",
          label: "Content Generation",
          items: require("./docs/api/content-generation/sidebar.ts").default,
        },
        {
          type: "category",
          label: "Content Evaluations",
          items: require("./docs/api/content-evaluations/sidebar.ts").default,
        },
        {
          type: "category",
          label: "Fact Check",
          items: require("./docs/api/fact-check/sidebar.ts").default,
        },
        {
          type: "category",
          label: "GraphQL",
          items: require("./docs/api/graphql/sidebar.ts").default,
        },
        {
          type: "category",
          label: "Inspector",
          items: require("./docs/api/inspector/sidebar.ts").default,
        },
        {
          type: "category",
          label: "KPI Events",
          items: require("./docs/api/events/sidebar.ts").default,
        },
        {
          type: "category",
          label: "Long Tail",
          items: require("./docs/api/long-tail/sidebar.ts").default,
        },
        {
          type: "category",
          label: "Manager",
          items: require("./docs/api/manager/sidebar.ts").default,
        },
        {
          type: "category",
          label: "Google Search Console",
          items: require("./docs/api/gsc-url-inspections/sidebar.ts").default,
        },
        {
          type: "category",
          label: "Middleware",
          items: require("./docs/api/middleware/sidebar.ts").default,
        },
        {
          type: "category",
          label: "Summarization",
          items: require("./docs/api/summarizer/sidebar.ts").default,
        },
        {
          type: "category",
          label: "Sitemap Generator",
          items: require("./docs/api/sitemap-generator/sidebar.ts").default,
        },
        {
          type: "category",
          label: "Query Fan-Out",
          items: require("./docs/api/query-fan-out/sidebar.ts").default,
        },
      ],
    },
  ],
};

module.exports = sidebars;
