name: Update SDK

# Define the events that trigger the workflow
on:
  push:
    branches:
      - main
    paths:
      - "api/**"
  workflow_dispatch:

jobs:
  update_api:
    # Define the OS and environment the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        target:
          - repository: wordlift/python-client
            path: python-client
          - repository: wordlift/ngx-api-client
            path: ngx-api-client

    steps:
      # Step 1: Checkout the first repository
      - name: Checkout repository
        uses: actions/checkout@v6

      # Step 2: Checkout the target repository
      - name: Checkout target repository
        uses: actions/checkout@v6
        with:
          repository: ${{ matrix.target.repository }}
          path: ${{ matrix.target.path }}
          token: ${{ secrets.GH_PAT }}

      # # step 3: Patch middleware api specification
      # - name: Apply patch to middleware.yaml
      #   run: git apply ./patches/fix_middleware_spec.patch

      - name: Copy content from current repo to target repo
        run: rm ${{ matrix.target.path }}/api/*.yaml && cp api/* ${{ matrix.target.path }}/api

      # Step 4: Commit and push the changes to the target repository
      - name: Commit and push changes
        run: |
          cd ${{ matrix.target.path }}
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m "Update api"
          git push origin main
